Fix vps and makeself - they now pass CI + syntax_analysis fix
binpash/benchmarks pull request #47
Opened 2024-12-27 23:22 UTC by Geoka1

2024-12-29 12:49 UTC, LLazarek requested changes
Tagging @vagos to look over this as well and make sure I'm not asking for unusual things :)

2024-12-29 12:49 UTC, LLazarek commented on makeself/run.sh
1. I don't think this script should go through the `makefile` indirection -- just execute the script that the makefile runs directly. Also, be sure to run it with the environment variable hook for the benchmarks -- refer to e.g. `unix50`'s `run.sh`.

2. All this setup for `shunit2` should be done in `deps.sh`, not here, unless I'm mistaken.

2024-12-29 12:49 UTC, LLazarek commented on makeself/verify.sh
This script shouldn't do the same thing as `run.sh` -- it shouldn't run the benchmark. Instead, it should inspect the outputs produced by `run.sh` to determine if it ran correctly. See `unix50`'s `verify.sh` for example

2024-12-29 12:49 UTC, LLazarek commented on makeself/makeself/test/run-tests.sh
> +	bash "./$test" || { echo "*** ERROR: Test '$test' failed!"; exit 1; }
We may want to modify this so that it uses `$BENCHMARK_SHELL` instead of `bash`?

2024-12-29 12:49 UTC, LLazarek commented on makeself/makeself/.err
Unless I'm mistaken, I don't think we want these output files (this, `.hash`, `.out`, and `release/`) committed?

2024-12-29 12:49 UTC, LLazarek commented on vps-audit/run.sh
> +"${main_script}" 2>&1 | tee "${log_file}"
Also need to use `$BENCHMARK_SHELL` here

2024-12-29 12:49 UTC, LLazarek commented on vps-audit/verify.sh
Could we do better than this by just filtering out the parts of the log that we expect to change (like current memory usage, or time) and then hashing the remaining content?

2024-12-29 12:49 UTC, LLazarek commented on vps-audit/verify.sh
> +[[ "$RESULTS_COUNT" -gt 0 ]] || fail "No result markers ([PASS], [WARN], [FAIL]) found in the report."
Otherwise I think we should do better than this: specify the exact sequence of result markers we expect, perhaps the associated messages

2024-12-29 12:49 UTC, LLazarek commented on infrastructure/syntax_analysis.py
Let's drop this from this PR since we already have #44

2025-01-06 10:16 UTC, Geoka1 commented
@vagos I believe this is good to merge now. Thank you!

2025-01-06 10:29 UTC, merged